export const MONTHS = [
  'January',
  'February',
  'March',
  'April',
  'May',
  'June',
  'July',
  'August',
  'September',
  'October',
  'November',
  'December',
];

export const DEFAULT_CATEGORIES = [
  {
    categoryName: 'immediate obligations',
    categoryLimitAmount: 0,
    expensesInCategory: [
      { expense: 'rent', amount: 0, limitAmount: 0 },
      { expense: 'electric', amount: 0, limitAmount: 0 },
      { expense: 'water', amount: 0, limitAmount: 0 },
      { expense: 'internet', amount: 0, limitAmount: 0 },
      { expense: 'groceries', amount: 0, limitAmount: 0 },
      { expense: 'gas', amount: 0, limitAmount: 0 },
    ],
  },
  {
    categoryName: 'true expenses',
    categoryLimitAmount: 0,
    expensesInCategory: [
      { expense: 'car maintenance', amount: 0, limitAmount: 0 },
      { expense: 'home maintenance', amount: 0, limitAmount: 0 },
      {
        expense: 'medical insurance',
        amount: 0,
        limitAmount: 0,
      },
      { expense: 'car insurance', amount: 0, limitAmount: 0 },
      { expense: 'home insurance', amount: 0, limitAmount: 0 },
    ],
  },
  {
    categoryName: 'quality of life',
    categoryLimitAmount: 0,
    expensesInCategory: [
      { expense: 'vacation', amount: 0, limitAmount: 0 },
      { expense: 'gym membership', amount: 0, limitAmount: 0 },
      { expense: 'education', amount: 0, limitAmount: 0 },
    ],
  },
  {
    categoryName: 'subscriptions',
    categoryLimitAmount: 0,
    expensesInCategory: [
      { expense: 'netflix', amount: 0, limitAmount: 0 },
      { expense: 'spotify', amount: 0, limitAmount: 0 },
    ],
  },
  {
    categoryName: 'fun',
    categoryLimitAmount: 0,
    expensesInCategory: [
      { expense: 'gaming', amount: 0, limitAmount: 0 },
      { expense: 'music', amount: 0, limitAmount: 0 },
      { expense: 'dining out', amount: 0, limitAmount: 0 },
    ],
  },
];

export const PIE_CHART_COLORS = [
  '#FF6384',
  '#36A2EB',
  '#FFCE56',
  '#79cf0b',
  '#fd1d6f',
  '#0aede8',
  '#769334',
  '#2a4e40',
  '#641c8d',
  '#971f56',
  '#584f41',
  '#37f1b4',
  '#32e957',
  '#7a10dd',
  '#298ca4',
  '#42d554',
  '#b67059',
  '#2950f0',
  '#c14104',
  '#a5dc13',
  '#2af2d9',
  '#f4792f',
  '#7c552d',
  '#fdc0f4',
  '#b0c7b2',
  '#55e7a1',
  '#4fbe44',
  '#e12b29',
  '#bf9855',
  '#a0273d',
  '#79cf0b',
  '#fb5b8b',
  '#2a0714',
  '#f69740',
  '#1735e0',
  '#197e46',
  '#765292',
  '#848b81',
  '#7d2205',
  '#ca76d9',
  '#31a33b',
  '#6aa2e0',
  '#7e0180',
  '#daf11c',
  '#061325',
  '#50c341',
  '#fe2cea',
  '#89ec63',
  '#27361f',
  '#c8df31',
  '#ae9b71',
  '#82802d',
  '#3a3895',
  '#dcfe5f',
  '#dcfe5f',
  '#1ef0f9',
];

export const DEFAULT_PREFERENCES = {
  darkTheme: false,
  displaySymbol: true,
  currency: '€',
};

export const AVAILABLE_LANGUAGES = ['en', 'si'];
